[project]
entry = "App"
koja = "0.19"
name = "remem"
version = "0.4.0"

[dependencies]
conn = { path = "lib/conn" }
pooler = { path = "lib/pooler" }
postgres = { github = "hpopp/postgres-koja", tag = "v0.4.0" }
trail = { path = "lib/trail" }
