[project]
entry = "App"
koja = "0.18"
name = "remem"
version = "0.2.1"

[dependencies]
conn = { path = "lib/conn" }
pooler = { path = "lib/pooler" }
postgres = { github = "hpopp/postgres-koja", tag = "v0.3.0" }
trail = { path = "lib/trail" }
